import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Banner.module.css'
//image
import bannerImg from '../public/images/banners/service.png'
import chat from '../public/images/icons/chat.png'
import call from '../public/images/icons/call.png'
//components
import Banner from '@/components/Banner'
import Availing from '@/components/Availing'
import Runner from '@/components/Runner'
import Online from '@/components/Online'
import Consult from '@/components/Consult'
import Content from '@/components/Content'
import Purchasers from '@/components/Purchasers'
import Testimonial from '@/components/Testimonial'


export default function AmazonServices() {

    const newTitle = <h1 className='font-60 fw-400 font-prime txt-white my-4'>Professional <span className='d-block txt-prime fw-700'>Amazon Marketing</span> Company Online</h1>


    const cta1 =
        <div className='bttns mt-3'>
            <Link className={`${styles.btnL} btons btns btnPrime`} href="#">
                <Image className='img-fluid chat' src={chat} alt='Amazon_Square' />
                Live Chat
            </Link>
            <Link className={`${styles.btnW} btons btns btnWhite`} href="#">
                <Image className='img-fluid call' src={call} alt='Amazon_Square' />
                +1 (408) 689-7746
            </Link>
        </div>

    const bannertext = [
        {
            title: newTitle,
            text: 'We offer the top amazon marketing services in California, covering Amazon SEO marketing services, Amazon PPC marketing services, Amazon social media marketing services, and Amazon email marketing services.',
            discuss: cta1,
            imageban: bannerImg,
            banner: 'serviceBanner'
        }
    ]

    return (
        <>
            <Head>
                <title>Amazon Square</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>

            {/* ========= Banner ========= */}
            {bannertext.map((item, i) =>
                <Banner key={i}
                    title={item.title}
                    text={item.text}
                    discuss={item.discuss}
                    imageban={item.imageban}
                    banner={item.banner}
                />
            )}

            {/* ========= Availing ========= */}
            <Availing />

            {/* ========= Runner ========= */}
            <Runner />

            {/* ========= Online ========= */}
            <Online />

            {/* ========= Consult ========= */}
            <Consult />

            {/* ========= Content ========= */}
            <Content />

            {/* ========= Purchasers ========= */}
            <Purchasers />

            {/* ========= Testimonial ========= */}
            <Testimonial />
        </>
    )
}
