import Head from 'next/head'
import Link from 'next/link'
import Banner from '@/components/Banner'


//image
import bannerImg from '../public/images/banners/home.png'

export default function Home() {

  const cta1 = <Link className='btns homeBtn btnPrime' href="#">Get A Quote</Link>

  const bannertext = [
    {
      title: 'Amazon SEO Services',
      subtitle: 'The Fast Lane To Revenue Growth',
      text: 'Amazon Listing Optimization That Encourage Online Shoppers to Buy',
      subtext: 'With our performance-oriented Amazon SEO services, we help your business and your products become the number one pick of buyers worldwide.',
      discuss: cta1,
      imageban: bannerImg,
      alignclass: 'homeBanner',
      banner: 'banner'
    }
  ]

  return (
    <>
      <Head>
        <title>Amazon Square</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*========= Banner =========*/}
      {bannertext.map((item, i) =>
        <Banner key={i}
          title={item.title}
          subtitle={item.subtitle}
          text={item.text}
          subtext={item.subtext}
          discuss={item.discuss}
          imageban={item.imageban}
          alignclass={item.alignclass}
          banner={item.banner}
        />
      )}

    </>
  )
}
