import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Banner.module.css'
//image
import bannerImg from '../public/images/banners/marketing.png'
import chat from '../public/images/icons/chat.png'
import call from '../public/images/icons/call.png'
//components
import Banner from '@/components/Banner'
import ContactFold from '@/components/ContactFold'
import Wasting from '@/components/Wasting'
import Rate from '@/components/Rate'
import Solutions from '@/components/Solutions'
import Clients from '@/components/Clients'
import Should from '@/components/Should'
import Convinced from '@/components/Convinced'
import Testimonial from '@/components/Testimonial'


export default function AmazonMarketing() {

    const newTitle = <h1 className='font-60 fw-300 font-prime txt-second mb-4 mt-5'>Make Your
        <span className='d-block txt-prime fw-700'>Product Visible</span> to A Larger Target Audience</h1>

    const cta1 =
        <div className='bttns mt-3'>
            <Link className={`${styles.btnL} btons btns btnPrime`} href="#">
                <Image className='img-fluid chat' src={chat} alt='Amazon_Square' />
                Live Chat
            </Link>
            <Link className={`${styles.btnW} btons btns btnSecond`} href="#">
                <Image className='img-fluid call' src={call} alt='Amazon_Square' />
                +1 (408) 689-7746
            </Link>
        </div>

    const bannertext = [
        {
            title: newTitle,
            subtext1: 'Amazon Square is a pioneering Amazon A++ marketing company that helps sellers, vendors, retailers, and business owners to excel in their businesses. Our A++ marketing approach focuses on corporate earnings, consumer desires, and societal interests. Hire the best Amazon A++ marketing professionals online now!',
            discuss: cta1,
            imageban: bannerImg,
            banner: 'marketingBanner'
        }
    ]

    return (
        <>
            <Head>
                <title>Amazon Square</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>

            {/* ========= Banner ========= */}
            {bannertext.map((item, i) =>
                <Banner key={i}
                    title={item.title}
                    subtext1={item.subtext1}
                    discuss={item.discuss}
                    imageban={item.imageban}
                    banner={item.banner}
                />
            )}

            {/* ========= ContactFold ========= */}
            <ContactFold />

            {/* ========= Wasting ========= */}
            <Wasting />

            {/* ========= Rate ========= */}
            <Rate />

            {/* ========= Solutions ========= */}
            <Solutions />

            {/* ========= Clients ========= */}
            <Clients />

            {/* ========= Should ========= */}
            <Should />

            {/* ========= Excellent ========= */}
            <Convinced />

            {/* ========= Testimonial ========= */}
            <Testimonial />
        </>
    )
}
